### ISSUE TITLE
迁移文档内容到仓库内

### ISSUE THREAD

**Issue by iceBear67** [SmileYik/LuaInMinecraftBukkt#2]
仅作参考建议..

---
我认为这是一个很棒的项目！但是阅读文档的过程中我发现您使用自己的博客对一系列教程进行托管。虽然这并非不可，但是放在博客上实有不妥~~（而且我阅览您文章的时候就发现突然回不去教学章节了）~~，并且不利于多人协作，如贡献新特性，更新文档等。

...

因此，希望您可以考虑将文档/教学内容迁移到仓库中。注意到您博客发布文章采用了一种 Markdown 方言，**若您有意愿迁移**，可以参考一下使用 `docsify` 和 GitHub Wiki..

**Comment by SmileYik** [comment]
原来还是有人喜欢这插件啊, mcbbs一点反应都没有还以为没人喜欢呢

教程转到了github wiki上, 就是有些链接他还是跳到我博客上的, 那些链接还没改

https://github.com/SmileYik/LuaInMinecraftBukkt/wiki
